### ISSUE TITLE
[Files] Layout for latest and recommended download sections broken on Safari

### ISSUE THREAD

**Issue by JDLogic** [MinecraftForge/Web#1]
<img width="1426" alt="screen shot 2017-06-14 at 3 26 17 pm" src="https://user-images.githubusercontent.com/6103327/27185948-be457de4-519b-11e7-82a4-212a48e64539.png">

If there is anything I can do to help resolve this issue, then please let me know as I am glad to help out.

P.S. The new sites look great BTW!

**Comment by marvin-roesch** [comment]
Mind providing me with some details about your browser and window size/screen resolution?

**Comment by JDLogic** [comment]
Safari version: 10.1.2
Window size: 2880x1650
Screen Resolution: 2880x1800

It also happens on my second monitor which is 1920x1080.

**Comment by marvin-roesch** [comment]
There appears to be a bug with Safari which is causing this. I set `flex-basis` to `0` for all links in the promotions area and Safari uses that rather than the calculated width of each element for its wrapping calculations. I can work around it with a sufficiently large base value, so I'll do that for now.
