### ISSUE TITLE
Current Web Dev Here with SEO knowledge

### ISSUE THREAD

**Issue by BitForger** [MinecraftForge/Web#2]
I can't really know what needs work without seeing your html but generally the list goes.
- Don't load `meta` keywords tag / don't even use it at all
- Make descriptive unique titles
- Only one h1 tag per page
- Keep DOM structure simple and easy to read
- Have a sitemap
- Upload sitemap to Google Webmaster Tools

**Comment by marvin-roesch** [comment]
Thanks for providing help. I'll commit the HTML templates some time this week, but I have to double check them for sensitive data and I'd also like to clean them up a bit. I'll see about implementing your current suggestions.

**Comment by marvin-roesch** [comment]
@BitForger, I've added the current HTML templates to the repo. Feel free to PR any changes that would improve searchability or ask back if you need have any questions regarding the templates' structure.

**Comment by BitForger** [comment]
@PaleoCrafter I don't see anything in particular that I would change. I would suggest looking into some of google's tools and see what they say.

**Comment by sitedyno** [comment]
I'll throw my $.02 in. I don't currently do any SEO, but have done a little bit of SEO research in the past.

`http://files.minecraftforge.net/` is effectively your main landing page. It looks to be the first minecraftforge.net result in most of the keyword searches I've tried. `http://files.minecraftforge.net/` is the top result because you have more links back to the download page than any other page on the site. I think the page can be improved to provide more context for humans and for search engines.

There was some discussion on "the twitters" about fake download sites etc. I don't think you will be able to get rid of them, but I think the page should provide more context to allow searchers and search engines to more easily identify the site they really want to visit/rank.

I'd recommend the page title be something like:

> Official Download Site for Forge: The Minecraft Mod Loader and Modding API

I'd also include a smallish blurb on the page explaining what Forge is and that this is the `Official` place to get it:

> The Official download site for Forge. Forge is a mod loader and modding API for the JAVA version of Minecraft. Forge gives modders the foundation to build their mods on. Forge increases inter mod compatibility and provides the tools modders need to succeed.

Most of the other search results I saw give a brief explanation of what Forge is and why it's beneficial.

Any link on your site that links back to `http://files.minecraftforge.net/` should have similar keywords/phrases in the link text and title attribute:
`<a href="http://files.minecraftforge.net/" title="Official Download Site for Forge: The Minecraft Mod Loader and Modding API">Official Download Site for Forge: The Minecraft Mod Loader and Modding API</a>`

To really drive home that this is the *right* place, encourage other sites that link back to you to use similar language/phrases. Maybe even create a widget to generate the links that people use to link back, make it stupid simple for them to use the language you prefer.

**Comment by BitForger** [comment]
@sitedyno Good points, I often forget details of wording like that and look at it from a developers perspective.

**Comment by sfxworks** [comment]
Currently studying SEO

The meta description key is important. 
Site structure and organization plays a huge role
Keywords should be fused with paths, title, and h1s. (Build a list using keyword tools such as google adwords (its free)) https://adwords.google.com/home/tools/keyword-planner/

Microdata on web pages is important. Look up and add the proper ones.
Example: things to add to a forge API documentation page http://schema.org/APIReference
sitemaps are also important https://www.sitemaps.org/protocol.html

Additionally:

Other sites linking to you will increase your authority, therefore, the likelihood other sites can overtake you will decrease. Consider using social media to promote your site or encouraging others to link back to your site in mod author's online project descriptions.
